# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-31 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('topic_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Topic'),
        ),
    ]
