# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 3, 8, 55, 33, 568000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
