# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180203_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='published_date',
        ),
    ]
