# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_blogs_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
