# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_blogs_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
