# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180203_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
