# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 21:33
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_blogs_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=django.contrib.auth.models.User, max_length=250)),
                ('mail', models.CharField(default=django.contrib.auth.models.User, max_length=250)),
                ('profile_pic', models.FileField(upload_to=b'')),
                ('blogposts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Blogs')),
            ],
        ),
    ]
