# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 21:37
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='mail',
            field=models.CharField(max_length=250, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='user_name',
            field=models.CharField(max_length=250, verbose_name=django.contrib.auth.models.User),
        ),
    ]
