# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180228_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='blogposts',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
