# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20180301_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
