# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
