# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
