# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20180531_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default=datetime.datetime(2018, 6, 9, 19, 24, 38, 387000, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
