# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, default='blank-profile-picture-973460_640.png', null=True, upload_to=b''),
        ),
    ]
