# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20180613_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_pic',
            field=models.FileField(default='default-bigcover.jpg', upload_to=b''),
        ),
    ]
